imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

parameters:
    database_name: peya-symfony-cache-test
    cache_prefix: test
    cache_db: 2