# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    database_service:
        class:        AppBundle\Service\DatabaseService
        arguments:    ["%database_host%", "%database_port%", "%database_name%"]
    cache_service:
        class:        AppBundle\Service\CacheService
        arguments:    ["%cache_host%", "%cache_port%", "%cache_prefix%", "%cache_db%", '@database_service']
    validator_service:
        class:        AppBundle\Service\ValidatorService